#!/usr/bin/env bash

SCRIPT=`realpath $0`

readonly BASH_BINARY="$(which bash)"
declare -x PREVIEW_ID="preview"

declare -x TMP_FOLDER="/tmp/nvim-telescope-media"
mkdir -p $TMP_FOLDER

function render_at_size {
  if ! command -v chafa &> /dev/null; then
      echo "chafa could not be found in your path,\nplease install it to display media content"
      exit
  fi

  max_width="${1}"
  max_height="${2}"
  img_path="${3}"
  chafa --center=on --clear "${img_path}"
  if command -v file > /dev/null 2>&1; then
    file "${img_path}"
  fi

}

function svg {
  if ! command -v rsvg-convert &> /dev/null; then
    echo "rsvg-convert could not be found in your path,\nplease install it to display media content"
    exit
  fi
  readonly converted_img_path="${TMP_FOLDER}/rsvg-convert.png"
  img_path="${3}"
  rsvg-convert "${img_path}" -o "${converted_img_path}"
  
  render_at_size "${1}" "${2}" "${converted_img_path}"
}

function pdfpreview {
  if ! command -v pdftoppm &> /dev/null; then
      printf "pdftoppm could not be found in your path,\nplease install it to display pdf previews"
      exit
  fi
  readonly converted_pdf_img_path="${TMP_FOLDER}/pdftoppm-convert"
  img_path="${3}"
  error_message=$(pdftoppm -png -singlefile "${img_path}" "${converted_pdf_img_path}" 2>&1)
  if [ $? -ne 0 ]; then
    printf "Cann't convert the file, check if the file have a password, error: %s" "$error_message"
    exit
  fi
  render_at_size "${1}" "${2}" "${converted_pdf_img_path}.png"
}

function draw_preview {
    if [[ "$1" == "imagepreview" ]]; then
      render_at_size "${5}" "${6}" "${2}" "${7}"

    elif [[ "$1" == "gifpreview" ]]; then
      render_at_size "${5}" "${6}" "${2}" "${7}"

    elif [[ "$1" == "videopreview" ]]; then
      if ! command -v ffmpegthumbnailer &> /dev/null; then
        echo "ffmpegthumbnailer could not be found in your path,\nplease install it to display video previews"
        exit
      fi
      path="${2##*/}"
      ffmpegthumbnailer -i "$2" -o "${TMP_FOLDER}/${path}.png" -s 0 -q 10
      clear
      render_at_size "${5}" "${6}" "${TMP_FOLDER}/${path}.png" "${7}"
    fi
}

function parse_options {
    extension="${1##*.}"
    echo -e "Loading preview..\nFile: $1"
    case $extension in
    jpg | png | jpeg | webp)
        draw_preview  imagepreview "$1" $2 $3 $4 $5 $6
    ;;

    svg)
        svg $4 $5 "$1"
    ;;

    gif)
        draw_preview  gifpreview "$1" $2 $3 $4 $5 $6
    ;;

    avi | mp4 | wmv | dat | 3gp | ogv | mkv | mpg | mpeg | vob |  m2v | mov | webm | mts | m4v | rm  | qt | divx)
        draw_preview  videopreview "$1" $2 $3 $4 $5 $6
    ;;

    pdf | epub)
        pdfpreview $4 $5 "$1"
    ;;

    *)
    echo -n "unknown file $1"
    ;;
    esac
}

parse_options "${@}"
read
